# Generated by Django 2.2.7 on 2019-12-08 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 8, 15, 59, 54, 461095), verbose_name='Posted'),
        ),
    ]
