# Generated by Django 2.2.7 on 2019-12-15 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191210_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(db_index=True, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('band', models.TextField(verbose_name='Band')),
                ('art', models.FileField(upload_to='uploads/')),
                ('released', models.DateTimeField(default=datetime.datetime(2019, 12, 15, 9, 44, 50, 849536), verbose_name='Released')),
            ],
            options={
                'verbose_name': 'Items',
                'verbose_name_plural': 'Items',
                'db_table': 'Items',
                'ordering': ['-item_id'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 15, 9, 44, 50, 849536), verbose_name='Posted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 15, 9, 44, 50, 849536), verbose_name='Date'),
        ),
    ]
