# Generated by Django 2.2.7 on 2019-12-17 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191215_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 17, 23, 0, 33, 323468), verbose_name='Posted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 17, 23, 0, 33, 323468), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_cart',
            field=models.BooleanField(default=False, verbose_name='In cart'),
        ),
        migrations.AlterField(
            model_name='item',
            name='released',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 23, 0, 33, 323468), verbose_name='Released'),
        ),
    ]
