# Generated by Django 3.0.6 on 2020-05-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200521_1623'),
        ('app', '0028_auto_20200521_0138'),
    ]

    operations = [
    ]
